theme: noesya-hugo-theme
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  ecosystem: works
  breadcrumb:
    position: none
  summary:
    position: content
  posts:
    date_format: "2006"
    index:
      show_description: false
  seo:
    title:
      separator: "â€¢"
  image_sizes:
    design_system:
      lightbox:
        disabled: true
      hero:
        mobile:   400
        tablet:   1024
        desktop:  1920
    blocks:
      call_to_action:
        mobile:   400
        tablet:   1024
        desktop:  1920
      image:
        mobile:   480
        tablet:   768
        desktop:  960
      gallery:
        carousel:
          mobile:   400
          tablet:   1024
          desktop:  1920
        grid:
          mobile:   400
          tablet:   400
          desktop:  400
    sections:
      posts:
        hero:
          mobile:   400
          tablet:   1024
          desktop:  1920
        hero_single:
          mobile:   400
          tablet:   1024
          desktop:  1920
        item:
          mobile:   350
          tablet:   450
          desktop:  900